name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker images
      run: |
        services=("account-service" "api-gateway" "centralized-logging" "notification-service" "trading-service" "wallet-service")
        for service in "${services[@]}"; do
          docker build -t rashmisharmila/$service:latest ./$service
          docker push rashmisharmila/$service:latest
        done

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig
      run: |
        aws eks --region us-east-1 update-kubeconfig --name micro_service

    - name: Run unit tests
      run: |
        services=("account-service" "api-gateway" "centralized-logging" "notification-service" "trading-service" "wallet-service")
        for service in "${services[@]}"; do
          cd $service
          pip install -r requirements.txt
          cd ..
        done

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/account-service.yaml --validate=false
        kubectl apply -f kubernetes/api-gateway.yaml --validate=false
        kubectl apply -f kubernetes/centralized-logging.yaml --validate=false
        kubectl apply -f kubernetes/notification-service.yaml --validate=false
        kubectl apply -f kubernetes/trading-service.yaml --validate=false
        kubectl apply -f kubernetes/wallet-service.yaml --validate=false

    - name: Wait for rollouts
      run: |
        kubectl rollout status deployment/account-service
        kubectl rollout status deployment/api-gateway
        kubectl rollout status deployment/centralized-logging
        kubectl rollout status deployment/notification-service
        kubectl rollout status deployment/trading-service
        kubectl rollout status deployment/wallet-service

    - name: Clean up
      run: |
        rm -f kubeconfig.yaml
